from dataclasses import dataclass, field
from typing import Any, Optional

from app.common.enums import DatasetDomain


@dataclass(slots=True, frozen=True)
class QualityReport:
    """
    Immutable report detailing dataset quality metrics.
    """

    overall_score: float
    completeness_score: float
    uniqueness_score: float
    validity_score: float
    total_issues: int
    issues: tuple[str, ...] = field(default_factory=tuple)
    evidence: tuple[str, ...] = field(default_factory=tuple)


@dataclass(slots=True, frozen=True)
class StatisticalSummary:
    """
    Immutable statistical summary across all columns in a dataset.
    """

    total_rows: int
    numeric_columns_count: int
    categorical_columns_count: int
    date_columns_count: int
    column_summaries: dict[str, dict[str, float]] = field(default_factory=dict)
    evidence: tuple[str, ...] = field(default_factory=tuple)


@dataclass(slots=True, frozen=True)
class CorrelationResult:
    """
    Immutable result of correlation analysis between two numeric columns.
    """

    column_a: str
    column_b: str
    coefficient: float
    correlation_type: str  # e.g., 'strong_positive', 'strong_negative', 'moderate'
    confidence: float
    reasoning: str
    # How sure we are it is not noise. `survived_fdr` is False until the pipeline has corrected across ALL tests.
    p_value: Optional[float] = None
    q_value: Optional[float] = None  # Benjamini-Hochberg adjusted p-value
    effect_size: Optional[float] = None  # |r| (correlation, regression) or |tau| (Mann-Kendall)
    n: int = 0
    survived_fdr: bool = False


@dataclass(slots=True, frozen=True)
class TrendResult:
    """
    Immutable result of time-series or trend analysis on a metric over time.
    """

    time_column: str
    metric_column: str
    direction: str  # e.g., 'increasing', 'decreasing', 'stable', 'volatile'
    slope: float
    growth_rate_pct: float
    confidence: float
    reasoning: str
    # How sure we are it is not noise. `survived_fdr` is False until the pipeline has corrected across ALL tests.
    p_value: Optional[float] = None
    q_value: Optional[float] = None  # Benjamini-Hochberg adjusted p-value
    effect_size: Optional[float] = None  # |r| (correlation, regression) or |tau| (Mann-Kendall)
    n: int = 0
    survived_fdr: bool = False
    test_method: str = ""  # linregress | mann-kendall


@dataclass(slots=True, frozen=True)
class OutlierReport:
    """
    Immutable report of outlier detection for a column.
    """

    column_name: str
    outlier_count: int
    outlier_percentage: float
    method_used: str  # e.g., 'IQR', 'Z-score'
    outlier_bounds: tuple[float, float]
    confidence: float
    reasoning: str


@dataclass(slots=True, frozen=True)
class PatternReport:
    """
    Immutable report of identified distribution patterns or rules (e.g. Pareto 80/20).
    """

    pattern_type: str  # e.g., 'pareto_80_20', 'seasonality', 'clustering'
    description: str
    affected_columns: tuple[str, ...] = field(default_factory=tuple)
    confidence: float = 0.0
    reasoning: str = ""


@dataclass(slots=True, frozen=True)
class BusinessAnomaly:
    """
    Immutable report of a domain-aware business rule anomaly.
    """

    anomaly_title: str
    severity: str  # 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'
    affected_entity: str
    metric_name: str
    observed_value: float
    expected_value: float
    deviation_pct: float
    confidence: float
    reasoning: str
    evidence: tuple[str, ...] = field(default_factory=tuple)


@dataclass(slots=True, frozen=True)
class InsightCandidate:
    """
    Immutable executive insight generated by synthesizing intelligence reports.
    """

    title: str
    category: str  # 'QUALITY', 'TREND', 'CORRELATION', 'ANOMALY', 'BUSINESS'
    impact: str  # 'HIGH', 'MEDIUM', 'LOW'
    description: str
    actionable_recommendation: str
    confidence: float
    reasoning: str
    evidence: tuple[str, ...] = field(default_factory=tuple)


@dataclass(slots=True, frozen=True)
class DataIntelligenceReport:
    """
    Unified immutable report synthesizing all data intelligence plugin findings.
    """

    quality_report: QualityReport
    statistical_summary: StatisticalSummary
    correlations: tuple[CorrelationResult, ...] = field(default_factory=tuple)
    trends: tuple[TrendResult, ...] = field(default_factory=tuple)
    outliers: tuple[OutlierReport, ...] = field(default_factory=tuple)
    patterns: tuple[PatternReport, ...] = field(default_factory=tuple)
    business_anomalies: tuple[BusinessAnomaly, ...] = field(default_factory=tuple)
    insights: tuple[InsightCandidate, ...] = field(default_factory=tuple)
    domain: DatasetDomain = DatasetDomain.UNKNOWN
    overall_health_score: float = 100.0
    # Multiple-testing bookkeeping: every correlation pair and trend tested, corrected together.
    tests_run: int = 0
    rejected_as_noise: int = 0  # failed the false-discovery-rate correction
    below_effect_threshold: int = 0  # survived it, but too weak to report
    fdr_q: float = 0.05
