import React from 'react';
import { Card } from '../../../components/ui/Card';
import { Badge } from '../../../components/ui/Badge';
import { Monitor, Download, Globe, Code, FileSpreadsheet } from 'lucide-react';

export const PowerBIInstructionGuide: React.FC = () => {
  return (
    <Card glass className="p-6 border-primary/30">
      <div className="flex items-center justify-between mb-4 pb-3 border-b border-border">
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Monitor className="w-5 h-5 text-primary" />
          <span>How to Connect PowerPilot to Power BI Desktop</span>
        </h3>
        <Badge variant="primary">4 Integration Options</Badge>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-sm">
        {/* Method 1: Copy DAX Measures */}
        <div className="p-4 bg-surface rounded-xl border border-border space-y-2">
          <div className="flex items-center gap-2 font-bold text-white">
            <Code className="w-4 h-4 text-purple-400" />
            <span>Option 1: Copy DAX Measures</span>
          </div>
          <p className="text-xs text-gray-300">
            Open Power BI Desktop $\rightarrow$ Click <strong>New Measure</strong> in Modeling tab $\rightarrow$ Paste the DAX code snippet generated by PowerPilot.
          </p>
        </div>

        {/* Method 2: Import BIM Tabular Schema */}
        <div className="p-4 bg-surface rounded-xl border border-border space-y-2">
          <div className="flex items-center gap-2 font-bold text-white">
            <Download className="w-4 h-4 text-success" />
            <span>Option 2: Import Tabular Model (.bim)</span>
          </div>
          <p className="text-xs text-gray-300">
            Download the <code>.bim</code> model file $\rightarrow$ Open in <strong>Tabular Editor</strong> or import into Analysis Services / Power BI workspace.
          </p>
        </div>

        {/* Method 3: Power Query M Transformation */}
        <div className="p-4 bg-surface rounded-xl border border-border space-y-2">
          <div className="flex items-center gap-2 font-bold text-white">
            <FileSpreadsheet className="w-4 h-4 text-warning" />
            <span>Option 3: Power Query M Transformations</span>
          </div>
          <p className="text-xs text-gray-300">
            In Power BI Desktop $\rightarrow$ Click <strong>Transform Data</strong> $\rightarrow$ Open Advanced Editor $\rightarrow$ Paste Power Query (M) code.
          </p>
        </div>

        {/* Method 4: Live REST API Connector */}
        <div className="p-4 bg-surface rounded-xl border border-border space-y-2">
          <div className="flex items-center gap-2 font-bold text-white">
            <Globe className="w-4 h-4 text-primary" />
            <span>Option 4: Live Web REST API Connector</span>
          </div>
          <p className="text-xs text-gray-300">
            Click <strong>Get Data</strong> $\rightarrow$ Select <strong>Web</strong> $\rightarrow$ Enter URL: <code>http://localhost:8000/api/v1/intelligence/analyze-csv</code>.
          </p>
        </div>
      </div>
    </Card>
  );
};
