from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from app.common.logger import get_logger
from app.core.config import Settings, get_settings
from app.datasets.service import DatasetService, get_dataset_service
from app.intelligence.llm.llm_copilot import GroundedAnswer, LlmCopilotService

router = APIRouter(prefix="/api/v1/copilot", tags=["AI Copilot"])
logger = get_logger("CopilotRoute")


def get_copilot_service(settings: Settings = Depends(get_settings)) -> LlmCopilotService:
    """Per-request service. Cheap to build; the Anthropic client is made lazily."""
    return LlmCopilotService(settings=settings)


class CopilotQuery(BaseModel):
    """A question asked against an already-registered dataset."""

    dataset_id: str = Field(..., min_length=1, description="Id returned by the analyze endpoint")
    query: str = Field(..., min_length=1, max_length=2000, description="Natural language question")


@router.get("/status")
def copilot_status(settings: Settings = Depends(get_settings)):
    """Which engine will answer, so the UI can say so up front.

    Never returns the API key.
    """
    return {
        "status": "success",
        "llm_enabled": settings.llm_enabled,
        "model": settings.llm_model if settings.llm_enabled else None,
        "engine": "llm" if settings.llm_enabled else "rules",
        "detail": (
            f"Answers are generated by {settings.llm_model}, grounded in the dataset's "
            "computed analysis and verified before being returned."
            if settings.llm_enabled
            else (
                "Answers come from the deterministic analysis engine. Set "
                "POWERPILOT_ANTHROPIC_API_KEY to enable natural-language answering."
            )
        ),
    }


@router.post("/ask")
def ask_copilot(
    payload: CopilotQuery,
    service: DatasetService = Depends(get_dataset_service),
    copilot: LlmCopilotService = Depends(get_copilot_service),
):
    """Answer a natural language BI question grounded in a registered dataset.

    The answer is derived entirely from that dataset's computed analysis. When a
    language model is configured it phrases the answer, but it is given only the
    analysis -- never the data -- and every figure it states is verified against
    the analysis before the response is returned. If verification fails, or the
    model is unavailable, the deterministic engine answers instead and the
    response says so.
    """
    analysis = service.get_analysis(payload.dataset_id)

    logger.info(
        f"Copilot query for dataset {payload.dataset_id} "
        f"('{analysis.record.filename}'): {payload.query[:120]}"
    )
    answer: GroundedAnswer = copilot.ask(payload.query, analysis.result)

    return {
        "status": "success",
        "dataset_id": payload.dataset_id,
        "dataset_name": analysis.record.filename,
        "query": payload.query,
        "answer": answer.answer,
        "intent": answer.intent,
        "evidence": list(answer.evidence),
        "recommended_actions": list(answer.recommended_actions),
        "suggested_followups": list(answer.suggested_followups),
        # Provenance: which engine answered, whether its figures were checked,
        # and why it fell back if it did.
        "source": answer.source,
        "verified": answer.verified,
        "verification_note": answer.verification_note,
        "fallback_reason": answer.fallback_reason,
    }
