import React, { useState, useEffect } from 'react';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { Badge } from '../../../components/ui/Badge';
import { useUploadStore } from '../../../store/useUploadStore';
import { useToast } from '../../../hooks/useToast';
import { ExportService } from '../../../services/exportService';
import { BrandingSettingsCard } from './BrandingSettingsCard';
import {
  Download,
  Mail,
  History,
  FileSpreadsheet,
  FileText,
  FileCode,
  Globe,
  Code,
  Send,
  CheckCircle2,
} from 'lucide-react';

export const ExportCenterView: React.FC = () => {
  const { file } = useUploadStore();
  const { showSuccess, showError } = useToast();

  const [activeTab, setActiveTab] = useState<'downloads' | 'email' | 'history'>('downloads');
  const [companyName, setCompanyName] = useState('Enterprise Organization');
  const [preparedFor, setPreparedFor] = useState('Executive Leadership Team');
  const [preparedBy, setPreparedBy] = useState('PowerPilot Intelligence Platform');

  const [loadingExport, setLoadingExport] = useState<string | null>(null);
  const [recipients, setRecipients] = useState('');
  const [emailSubject, setEmailSubject] = useState('PowerPilot Executive BI Report');
  const [emailBody, setEmailBody] = useState(
    'Please find attached the executive intelligence report and data quality audit generated by PowerPilot.'
  );
  const [isSendingEmail, setIsSendingEmail] = useState(false);

  const [historyList, setHistoryList] = useState<any[]>([]);

  const fetchHistory = async () => {
    try {
      const res = await ExportService.getExportHistory();
      if (res.history) {
        setHistoryList(res.history);
      }
    } catch (err) {
      // Ignore
    }
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const handleExport = async (key: string, fn: () => Promise<void>, label: string) => {
    if (!file) {
      showError('No File Selected', 'Please upload a dataset CSV file on the home screen first.');
      return;
    }
    setLoadingExport(key);
    try {
      await fn();
      showSuccess('Export Complete', `Successfully downloaded ${label}.`);
      await fetchHistory();
    } catch (err: any) {
      showError('Export Failed', err.message);
    } finally {
      setLoadingExport(null);
    }
  };

  const handleSendEmail = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file) {
      showError('No File Selected', 'Please upload a dataset CSV file first.');
      return;
    }
    if (!recipients) {
      showError('Missing Recipients', 'Please enter at least one recipient email address.');
      return;
    }
    setIsSendingEmail(true);
    try {
      const res = await ExportService.sendEmailDistribution(file, {
        recipients,
        subject: emailSubject,
        body_message: emailBody,
      });
      showSuccess('Distribution Sent', res.message);
      await fetchHistory();
    } catch (err: any) {
      showError('Email Failed', err.message);
    } finally {
      setIsSendingEmail(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Branding Config Section */}
      <BrandingSettingsCard
        companyName={companyName}
        setCompanyName={setCompanyName}
        preparedFor={preparedFor}
        setPreparedFor={setPreparedFor}
        preparedBy={preparedBy}
        setPreparedBy={setPreparedBy}
      />

      {/* Sub Tab Switcher */}
      <div className="flex items-center gap-2 border-b border-border pb-3">
        <button
          onClick={() => setActiveTab('downloads')}
          className={`flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg transition-colors ${
            activeTab === 'downloads' ? 'bg-primary text-white' : 'text-gray-400 hover:text-white'
          }`}
        >
          <Download className="w-4 h-4" />
          <span>Download Center</span>
        </button>

        <button
          onClick={() => setActiveTab('email')}
          className={`flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg transition-colors ${
            activeTab === 'email' ? 'bg-primary text-white' : 'text-gray-400 hover:text-white'
          }`}
        >
          <Mail className="w-4 h-4" />
          <span>Email Distribution</span>
        </button>

        <button
          onClick={() => {
            setActiveTab('history');
            fetchHistory();
          }}
          className={`flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg transition-colors ${
            activeTab === 'history' ? 'bg-primary text-white' : 'text-gray-400 hover:text-white'
          }`}
        >
          <History className="w-4 h-4" />
          <span>Export History</span>
        </button>
      </div>

      {/* Tab 1: Download Center */}
      {activeTab === 'downloads' && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Executive PDF */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-primary">
                  <FileText className="w-5 h-5" />
                  <h4 className="font-bold text-white">Executive PDF Report</h4>
                </div>
                <Badge variant="primary">PDF</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Multi-page executive report including Executive Briefing, Data Quality Grade, DAX measures, and Decision matrix.
              </p>
            </div>
            <Button
              isLoading={loadingExport === 'pdf'}
              onClick={() => handleExport('pdf', () => ExportService.exportPdfReport(file!, companyName, preparedFor), 'Executive PDF')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export PDF
            </Button>
          </Card>

          {/* Cleaned Dataset Excel */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-success">
                  <FileSpreadsheet className="w-5 h-5" />
                  <h4 className="font-bold text-white">Cleaned Dataset (.xlsx)</h4>
                </div>
                <Badge variant="success">EXCEL</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Cleaned dataset produced by Stage 1 DQPE with an embedded Audit Metadata sheet.
              </p>
            </div>
            <Button
              variant="secondary"
              isLoading={loadingExport === 'xlsx'}
              onClick={() => handleExport('xlsx', () => ExportService.exportCleanedData(file!, 'xlsx'), 'Cleaned Excel')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export XLSX
            </Button>
          </Card>

          {/* Word Document Report */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-warning">
                  <FileCode className="w-5 h-5" />
                  <h4 className="font-bold text-white">Executive Word Report</h4>
                </div>
                <Badge variant="warning">DOCX</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Fully editable Microsoft Word document report formatted with corporate typography.
              </p>
            </div>
            <Button
              variant="outline"
              isLoading={loadingExport === 'docx'}
              onClick={() => handleExport('docx', () => ExportService.exportDocxReport(file!, companyName, preparedFor), 'Word Document')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export DOCX
            </Button>
          </Card>

          {/* Data Dictionary */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-primary">
                  <FileSpreadsheet className="w-5 h-5" />
                  <h4 className="font-bold text-white">Data Dictionary (.xlsx)</h4>
                </div>
                <Badge variant="primary">SCHEMA</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Technical column specs, physical types, semantic types, sample values, and associated DAX KPIs.
              </p>
            </div>
            <Button
              variant="secondary"
              isLoading={loadingExport === 'dict'}
              onClick={() => handleExport('dict', () => ExportService.exportDataDictionary(file!), 'Data Dictionary')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export Dictionary
            </Button>
          </Card>

          {/* Interactive HTML */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-success">
                  <Globe className="w-5 h-5" />
                  <h4 className="font-bold text-white">Interactive HTML Report</h4>
                </div>
                <Badge variant="success">HTML</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Single-file web report with sidebar navigation, executive briefing, and decision cards.
              </p>
            </div>
            <Button
              variant="outline"
              isLoading={loadingExport === 'html'}
              onClick={() => handleExport('html', () => ExportService.exportHtmlReport(file!), 'Interactive HTML')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export HTML
            </Button>
          </Card>

          {/* Master Developer JSON */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-purple-400">
                  <Code className="w-5 h-5" />
                  <h4 className="font-bold text-white">Developer Master JSON</h4>
                </div>
                <Badge variant="purple">JSON</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Complete MasterIntelligenceResult JSON payload containing all 12 pipeline stage outputs.
              </p>
            </div>
            <Button
              variant="secondary"
              isLoading={loadingExport === 'json'}
              onClick={() => handleExport('json', () => ExportService.exportJson(file!), 'Developer JSON')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export JSON
            </Button>
          </Card>
        </div>
      )}

      {/* Tab 2: Email Distribution */}
      {activeTab === 'email' && (
        <Card glass className="p-6">
          <h3 className="text-lg font-bold text-white mb-2 flex items-center gap-2">
            <Mail className="w-5 h-5 text-primary" />
            <span>Automated Email Distribution Center</span>
          </h3>
          <p className="text-xs text-gray-400 mb-6">
            Distribute executive PDF reports and data quality audits asynchronously via SMTP / SendGrid / SES.
          </p>

          <form onSubmit={handleSendEmail} className="space-y-4 max-w-xl">
            <div>
              <label className="text-xs font-semibold text-gray-300 uppercase block mb-1">
                Recipient Email Addresses (Comma Separated)
              </label>
              <input
                type="text"
                value={recipients}
                onChange={(e) => setRecipients(e.target.value)}
                placeholder="ceo@company.com, cfo@company.com"
                className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-primary/50"
              />
            </div>

            <div>
              <label className="text-xs font-semibold text-gray-300 uppercase block mb-1">Subject Line</label>
              <input
                type="text"
                value={emailSubject}
                onChange={(e) => setEmailSubject(e.target.value)}
                className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-primary/50"
              />
            </div>

            <div>
              <label className="text-xs font-semibold text-gray-300 uppercase block mb-1">Message Body</label>
              <textarea
                rows={4}
                value={emailBody}
                onChange={(e) => setEmailBody(e.target.value)}
                className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-primary/50"
              />
            </div>

            <Button type="submit" isLoading={isSendingEmail} leftIcon={<Send className="w-4 h-4" />}>
              Distribute Email Report
            </Button>
          </form>
        </Card>
      )}

      {/* Tab 3: Export History */}
      {activeTab === 'history' && (
        <Card glass className="p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              <History className="w-5 h-5 text-primary" />
              <span>Export Audit History</span>
            </h3>
            <Button size="sm" variant="secondary" onClick={fetchHistory}>
              Refresh Log
            </Button>
          </div>

          {historyList.length === 0 ? (
            <p className="text-sm text-gray-400">No export activity recorded yet.</p>
          ) : (
            <div className="space-y-2 max-h-80 overflow-y-auto pr-2">
              {historyList.map((item, idx) => (
                <div key={idx} className="p-3 bg-surface rounded-lg border border-border flex items-center justify-between text-xs">
                  <div className="flex items-center gap-3">
                    <CheckCircle2 className="w-4 h-4 text-success" />
                    <div>
                      <span className="font-bold text-white">{item.dataset_name}</span>
                      <span className="text-gray-400 ml-2">({item.export_format})</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-4 text-gray-400">
                    <span>{(item.file_size_bytes / 1024).toFixed(1)} KB</span>
                    <span>{item.duration_ms} ms</span>
                    <span className="text-gray-300 font-mono">{item.timestamp}</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </Card>
      )}
    </div>
  );
};
