import React, { useState, useEffect } from 'react';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { Badge } from '../../../components/ui/Badge';
import { useAnalysisStore } from '../../../store/useAnalysisStore';
import { useToast } from '../../../hooks/useToast';
import { EmailStatus, ExportHistoryEntry, ExportService } from '../../../services/exportService';
import { BrandingSettingsCard } from './BrandingSettingsCard';
import {
  Download,
  Mail,
  History,
  FileSpreadsheet,
  FileText,
  FileCode,
  Globe,
  Code,
  CheckCircle2,
  Send,
  AlertTriangle,
} from 'lucide-react';

export const ExportCenterView: React.FC = () => {
  // Exports address the registered dataset by id — the CSV is never re-uploaded,
  // so they keep working after a page refresh.
  const { datasetId, currentDatasetName } = useAnalysisStore();
  const { showSuccess, showError } = useToast();

  const [activeTab, setActiveTab] = useState<'downloads' | 'email' | 'history'>('downloads');
  const [companyName, setCompanyName] = useState('Enterprise Organization');
  const [preparedFor, setPreparedFor] = useState('Executive Leadership Team');
  const [preparedBy, setPreparedBy] = useState('PowerPilot Intelligence Platform');

  const [loadingExport, setLoadingExport] = useState<string | null>(null);
  const [historyList, setHistoryList] = useState<ExportHistoryEntry[]>([]);

  const [emailStatus, setEmailStatus] = useState<EmailStatus | null>(null);
  const [recipients, setRecipients] = useState('');
  const [emailSubject, setEmailSubject] = useState('PowerPilot Executive BI Report');
  const [emailBody, setEmailBody] = useState(
    'Please find attached the executive intelligence report generated by PowerPilot.'
  );
  const [attach, setAttach] = useState<'pdf' | 'xlsx' | 'both'>('pdf');
  const [isSendingEmail, setIsSendingEmail] = useState(false);

  const datasetName = currentDatasetName ?? 'Dataset.csv';
  const branding = {
    company_name: companyName,
    prepared_for: preparedFor,
    prepared_by: preparedBy,
  };

  const fetchHistory = async () => {
    try {
      const res = await ExportService.getExportHistory();
      setHistoryList(res.history ?? []);
    } catch (err) {
      // History is diagnostic only; a failure here must not block exporting.
      showError(
        'Could not load export history',
        err instanceof Error ? err.message : 'Unknown error.'
      );
    }
  };

  useEffect(() => {
    fetchHistory();
    // Ask the server whether it can send at all, so the form is only offered when
    // a send would actually reach a mail server.
    ExportService.getEmailStatus()
      .then(setEmailStatus)
      .catch(() =>
        setEmailStatus({
          status: 'error',
          enabled: false,
          smtp_host: null,
          from_address: null,
          max_recipients: 0,
          detail: 'Could not reach the server to check email configuration.',
        })
      );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSendEmail = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!datasetId) {
      showError('No Active Dataset', 'Please upload and analyze a CSV dataset first.');
      return;
    }
    if (!recipients.trim()) {
      showError('Missing Recipients', 'Please enter at least one recipient email address.');
      return;
    }

    setIsSendingEmail(true);
    try {
      const result = await ExportService.sendEmail(
        datasetId,
        { recipients, subject: emailSubject, body_message: emailBody, attach },
        branding
      );
      showSuccess('Report Sent', result.message);
      await fetchHistory();
    } catch (err) {
      // The backend only resolves when a mail server accepted a recipient, so any
      // rejection here means the report genuinely did not go out.
      showError('Email Failed', err instanceof Error ? err.message : 'Unknown error.');
    } finally {
      setIsSendingEmail(false);
    }
  };

  const handleExport = async (key: string, fn: () => Promise<void>, label: string) => {
    if (!datasetId) {
      showError(
        'No Active Dataset',
        'Please upload and analyze a CSV dataset before exporting.'
      );
      return;
    }
    setLoadingExport(key);
    try {
      await fn();
      showSuccess('Export Complete', `Successfully downloaded ${label}.`);
      await fetchHistory();
    } catch (err) {
      showError('Export Failed', err instanceof Error ? err.message : 'Unknown error.');
    } finally {
      setLoadingExport(null);
    }
  };

  return (
    <div className="space-y-6">
      {/* Branding Config Section */}
      <BrandingSettingsCard
        companyName={companyName}
        setCompanyName={setCompanyName}
        preparedFor={preparedFor}
        setPreparedFor={setPreparedFor}
        preparedBy={preparedBy}
        setPreparedBy={setPreparedBy}
      />

      {/* Sub Tab Switcher */}
      <div className="flex items-center gap-2 border-b border-border pb-3">
        <button
          onClick={() => setActiveTab('downloads')}
          className={`flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg transition-colors ${
            activeTab === 'downloads' ? 'bg-primary text-white' : 'text-gray-400 hover:text-white'
          }`}
        >
          <Download className="w-4 h-4" />
          <span>Download Center</span>
        </button>

        <button
          onClick={() => setActiveTab('email')}
          className={`flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg transition-colors ${
            activeTab === 'email' ? 'bg-primary text-white' : 'text-gray-400 hover:text-white'
          }`}
        >
          <Mail className="w-4 h-4" />
          <span>Email Distribution</span>
        </button>

        <button
          onClick={() => {
            setActiveTab('history');
            fetchHistory();
          }}
          className={`flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg transition-colors ${
            activeTab === 'history' ? 'bg-primary text-white' : 'text-gray-400 hover:text-white'
          }`}
        >
          <History className="w-4 h-4" />
          <span>Export History</span>
        </button>
      </div>

      {/* Tab 1: Download Center */}
      {activeTab === 'downloads' && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Executive PDF */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-primary">
                  <FileText className="w-5 h-5" />
                  <h4 className="font-bold text-white">Executive PDF Report</h4>
                </div>
                <Badge variant="primary">PDF</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Multi-page executive report including Executive Briefing, Data Quality Grade, DAX measures, and Decision matrix.
              </p>
            </div>
            <Button
              isLoading={loadingExport === 'pdf'}
              onClick={() => handleExport('pdf', () => ExportService.exportPdfReport(datasetId!, datasetName, branding), 'Executive PDF')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export PDF
            </Button>
          </Card>

          {/* Cleaned Dataset Excel */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-success">
                  <FileSpreadsheet className="w-5 h-5" />
                  <h4 className="font-bold text-white">Cleaned Dataset (.xlsx)</h4>
                </div>
                <Badge variant="success">EXCEL</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Cleaned dataset produced by Stage 1 DQPE with an embedded Audit Metadata sheet.
              </p>
            </div>
            <Button
              variant="secondary"
              isLoading={loadingExport === 'xlsx'}
              onClick={() => handleExport('xlsx', () => ExportService.exportCleanedData(datasetId!, datasetName, 'xlsx'), 'Cleaned Excel')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export XLSX
            </Button>
          </Card>

          {/* Word Document Report */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-warning">
                  <FileCode className="w-5 h-5" />
                  <h4 className="font-bold text-white">Executive Word Report</h4>
                </div>
                <Badge variant="warning">DOCX</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Fully editable Microsoft Word document report formatted with corporate typography.
              </p>
            </div>
            <Button
              variant="outline"
              isLoading={loadingExport === 'docx'}
              onClick={() => handleExport('docx', () => ExportService.exportDocxReport(datasetId!, datasetName, branding), 'Word Document')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export DOCX
            </Button>
          </Card>

          {/* Data Dictionary */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-primary">
                  <FileSpreadsheet className="w-5 h-5" />
                  <h4 className="font-bold text-white">Data Dictionary (.xlsx)</h4>
                </div>
                <Badge variant="primary">SCHEMA</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Technical column specs, physical types, semantic types, sample values, and associated DAX KPIs.
              </p>
            </div>
            <Button
              variant="secondary"
              isLoading={loadingExport === 'dict'}
              onClick={() => handleExport('dict', () => ExportService.exportDataDictionary(datasetId!, datasetName), 'Data Dictionary')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export Dictionary
            </Button>
          </Card>

          {/* Interactive HTML */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-success">
                  <Globe className="w-5 h-5" />
                  <h4 className="font-bold text-white">Interactive HTML Report</h4>
                </div>
                <Badge variant="success">HTML</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Single-file web report with sidebar navigation, executive briefing, and decision cards.
              </p>
            </div>
            <Button
              variant="outline"
              isLoading={loadingExport === 'html'}
              onClick={() => handleExport('html', () => ExportService.exportHtmlReport(datasetId!, datasetName, branding), 'Interactive HTML')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export HTML
            </Button>
          </Card>

          {/* Master Developer JSON */}
          <Card hoverable className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2 text-purple-400">
                  <Code className="w-5 h-5" />
                  <h4 className="font-bold text-white">Developer Master JSON</h4>
                </div>
                <Badge variant="purple">JSON</Badge>
              </div>
              <p className="text-xs text-gray-300 mb-4">
                Complete MasterIntelligenceResult JSON payload containing all 12 pipeline stage outputs.
              </p>
            </div>
            <Button
              variant="secondary"
              isLoading={loadingExport === 'json'}
              onClick={() => handleExport('json', () => ExportService.exportJson(datasetId!, datasetName), 'Developer JSON')}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Export JSON
            </Button>
          </Card>
        </div>
      )}

      {/* Tab 2: Email Distribution.
          The form is only offered when the server reports SMTP as configured. An
          earlier version always showed it and always claimed success, while the
          backend sent nothing. */}
      {activeTab === 'email' && (
        <Card glass className="p-6">
          <h3 className="text-lg font-bold text-white mb-2 flex items-center gap-2">
            <Mail className="w-5 h-5 text-primary" />
            <span>Email Distribution</span>
          </h3>

          {emailStatus === null ? (
            <p className="text-xs text-gray-400">Checking email configuration…</p>
          ) : !emailStatus.enabled ? (
            <>
              <div className="flex items-start gap-3 p-4 mt-4 bg-warning/10 border border-warning/30 rounded-2xl max-w-2xl">
                <AlertTriangle className="w-4 h-4 text-warning mt-0.5 shrink-0" />
                <div className="space-y-2">
                  <span className="block text-sm font-semibold text-warning">
                    Email is not configured on this server
                  </span>
                  <p className="text-xs text-gray-300 leading-relaxed">{emailStatus.detail}</p>
                  <p className="text-xs text-gray-400 leading-relaxed">
                    Until then, use the Download Center to export the report and attach it
                    from your own mail client.
                  </p>
                </div>
              </div>

              <Button
                className="mt-5"
                variant="secondary"
                onClick={() => setActiveTab('downloads')}
                leftIcon={<Download className="w-4 h-4" />}
              >
                Go to Download Center
              </Button>
            </>
          ) : (
            <>
              <p className="text-xs text-gray-400 mb-6">
                Sending from <span className="font-mono text-gray-300">{emailStatus.from_address}</span>{' '}
                via <span className="font-mono text-gray-300">{emailStatus.smtp_host}</span>. Up to{' '}
                {emailStatus.max_recipients} recipients.
              </p>

              <form onSubmit={handleSendEmail} className="space-y-4 max-w-xl">
                <div>
                  <label
                    htmlFor="email-recipients"
                    className="text-xs font-semibold text-gray-300 uppercase block mb-1"
                  >
                    Recipient Email Addresses (Comma Separated)
                  </label>
                  <input
                    id="email-recipients"
                    type="text"
                    value={recipients}
                    onChange={(e) => setRecipients(e.target.value)}
                    placeholder="ceo@company.com, cfo@company.com"
                    className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-primary/50"
                  />
                </div>

                <div>
                  <label
                    htmlFor="email-subject"
                    className="text-xs font-semibold text-gray-300 uppercase block mb-1"
                  >
                    Subject Line
                  </label>
                  <input
                    id="email-subject"
                    type="text"
                    value={emailSubject}
                    onChange={(e) => setEmailSubject(e.target.value)}
                    className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-primary/50"
                  />
                </div>

                <div>
                  <label
                    htmlFor="email-body"
                    className="text-xs font-semibold text-gray-300 uppercase block mb-1"
                  >
                    Message Body
                  </label>
                  <textarea
                    id="email-body"
                    rows={4}
                    value={emailBody}
                    onChange={(e) => setEmailBody(e.target.value)}
                    className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-primary/50"
                  />
                </div>

                <div>
                  <label
                    htmlFor="email-attach"
                    className="text-xs font-semibold text-gray-300 uppercase block mb-1"
                  >
                    Attachments
                  </label>
                  <select
                    id="email-attach"
                    value={attach}
                    onChange={(e) => setAttach(e.target.value as 'pdf' | 'xlsx' | 'both')}
                    className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-primary/50"
                  >
                    <option value="pdf">Executive PDF report</option>
                    <option value="xlsx">Cleaned dataset (.xlsx)</option>
                    <option value="both">Both</option>
                  </select>
                </div>

                <Button type="submit" isLoading={isSendingEmail} leftIcon={<Send className="w-4 h-4" />}>
                  Send Report
                </Button>
              </form>
            </>
          )}
        </Card>
      )}

      {/* Tab 3: Export History */}
      {activeTab === 'history' && (
        <Card glass className="p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              <History className="w-5 h-5 text-primary" />
              <span>Export Audit History</span>
            </h3>
            <Button size="sm" variant="secondary" onClick={fetchHistory}>
              Refresh Log
            </Button>
          </div>

          {historyList.length === 0 ? (
            <p className="text-sm text-gray-400">No export activity recorded yet.</p>
          ) : (
            <div className="space-y-2 max-h-80 overflow-y-auto pr-2">
              {historyList.map((item, idx) => (
                <div key={idx} className="p-3 bg-surface rounded-lg border border-border flex items-center justify-between text-xs">
                  <div className="flex items-center gap-3">
                    <CheckCircle2 className="w-4 h-4 text-success" />
                    <div>
                      <span className="font-bold text-white">{item.dataset_name}</span>
                      <span className="text-gray-400 ml-2">({item.export_format})</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-4 text-gray-400">
                    <span>{(item.file_size_bytes / 1024).toFixed(1)} KB</span>
                    <span>{item.duration_ms} ms</span>
                    <span className="text-gray-300 font-mono">{item.timestamp}</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </Card>
      )}
    </div>
  );
};
